### ISSUE TITLE
ACF/ACF Pro Integration

### ISSUE THREAD

**Issue by jakub300** [pantheon-systems/pantheon-advanced-page-cache#133]
ACF has several field types for creating relationships, including [Post Object](https://www.advancedcustomfields.com/resources/post-object), [Relationship](https://www.advancedcustomfields.com/resources/relationship), [Taxonomy](https://www.advancedcustomfields.com/resources/taxonomy), User.

It would be great if posts/taxonomies/users referenced by ACF meta fields or ACF Gutenberg Blocks for current post or WP Query were automatically included in surrogate keys.

**Comment by danielbachhuber** [comment]
Hey @jakub300,

Thanks for the suggestion, and apologies for the late reply.

ACF integration would be pretty neat as a supplementary add-on plugin. It'd be more difficult to maintain in the primary plugin because:

1. There are lots of other plugins and themes we could potentially integrate with. It'd be impossible to integrate with all of them.
2. As ACF changes over time, we'd need to make sure the integration was kept up-to-date and backwards compatible.

If you were interested in writing and maintaining an add-on plugin, we'd be happy to link to it from the README 😄
