### ISSUE TITLE
How to handle Purge via plugin hooks

### ISSUE THREAD

**Issue by askmeoffers** [pantheon-systems/pantheon-advanced-page-cache#174]
Hi ,

We are using your platform and also this plugin 

Now we want to purge cache automatically when coupons are expired/added 
https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/

In the current scenario, this is not happening automatically via the plugin 

Please guide us 

Thanks
Team-askmeoffers.com

**Comment by danielbachhuber** [comment]
Hi @askmeoffers 👋 

It seems like you might want to flush the entire cache when coupons are expired or added, because you don't necessarily know which pages they appear on. To do so, you can call `pantheon_wp_clear_edge_all()` from the appropriate place in your codebase.

If you did want to purge specific URIs instead, you can do so with the `pantheon_wp_clear_edge_paths()` function:

```php
$paths = [ '/coupon-deal-offer-promo-store/oyorooms-com/' ];
pantheon_wp_clear_edge_paths( $paths );
```

Hope this helps! Let me know if you have any follow-up questions.
