### ISSUE TITLE
Move admin_post_pantheon_cache_delete_page from WP upstream

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/pantheon-advanced-page-cache#49]
![I](https://cloud.githubusercontent.com/assets/36432/19952115/07c07f00-a120-11e6-899c-aa69513e78fe.png)

Let's update the button text from "Delete Cache" to "Clear <item>'s Cache" so e.g:

"Clear Post's Cache"
or 
"Clear Page's Cache"

**Comment by danielbachhuber** [comment]
@ari-gold The upstream included this functionality across all URIs, so I decided to replicate that instead of making it specific to posts / pages.

Here's the button:

![image](https://cloud.githubusercontent.com/assets/36432/20160909/8ad0d726-a69f-11e6-86d9-263746fd1f20.png)

When the page cache is purged successfully, the text changes slightly to provide visual confirmation:

![image](https://cloud.githubusercontent.com/assets/36432/20160921/a4b75016-a69f-11e6-9144-008b7ae4cf74.png)

**Comment by ari-gold** [comment]
Nice! I think "Clear Page Cache" still isn't obvious that the button clears the cache for the current URL.  Let's go with "Clear URL Cache"

**Comment by danielbachhuber** [comment]
> Let's go with "Clear URL Cache"

👍

**Comment by ari-gold** [comment]
Looks good. Thanks @danielbachhuber!
