### ISSUE TITLE
Add guidance for custom queries

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/pantheon-advanced-page-cache#98]
@danielbachhuber, for sites with custom queries, is any extra work necessary to leverage this plugin? If so, can we document in the README?

**Comment by danielbachhuber** [comment]
> for sites with custom queries, is any extra work necessary to leverage this plugin?

Yes, there's a little bit of extra work that you need to do.

Ultimately, the challenge is that WordPress renders the page _after_ it sends its headers. Because surrogate keys are sent in a header, Pantheon Advanced Page Cache doesn't know what data is present in the page itself unless you explicitly tell it.

To tell PAPC which data is present in the page, you'll need to generate the data before headers are sent and then cache it for later rendering in the page. Here's an example:

```
/**
 * An example of pre-fetching a WP_Query to tag the
 * response with queried data. You'd use `papcx_wp_query()`
 * a second time within your template to use the data.
 */
add_filter( 'pantheon_wp_main_query_surrogate_keys', function( $keys ) {
	if ( is_home() ) {
		$query = papcx_wp_query( array(
			'post_type' => 'page',
		) );
		foreach( $query->posts as $post ) {
			$keys[] = 'post-' . $post->ID;
		}
	}
	return $keys;
});

/**
 * Register a 'papc-non-persistent' cache group to cache data
 * in a non-persistent manner. We only want data in this group
 * to be cached within the page request.
 */
add_action( 'init', function(){
	wp_cache_add_non_persistent_groups( array( 'papc-non-persistent' ) );
});

/**
 * Helper function to instantiate a WP_Query object only
 * once per page request.
 *
 * @param array $args Arguments to pass to WP_Query.
 * @return WP_Query
 */
function papcx_wp_query( $args = array() ) {
	$cache_key = md5( serialize( $args ) );
	// WP_Query object will be in cache the second time we use the function.
	$cache_value = wp_cache_get( $cache_key, 'papc-non-persistent' );
	if ( false !== $cache_value ) {
		return $cache_value;
	}
	$query = new WP_Query( $args );
	wp_cache_set( $cache_key, $query, 'papc-non-persistent' );
	return $query;
}
```

> If so, can we document in the README?

Sure thing: #99

**Comment by stevector** [comment]
Thanks @danielbachhuber! I don't have permission to merge in this repo. @joshkoenig, do you?

**Comment by danielbachhuber** [comment]
@stevector I can merge, no problem (although it'd be nice if you had access anyway).
